### ISSUE TITLE
Switch from ssh to https connection

### ISSUE THREAD

**Issue by anntzer** [cakoose/import-pull-request#2]
I suggest switching from ssh to https for the connection -- https always work whereas ssh requires, well, a ssh keypair which may or may not be present.  Github also recommends https over ssh.

This amounts to the following patch

```
@@ -64,7 +64,7 @@ def _main():
     title, state, target_branch, source_repo, source_branch = fetch_pr_info(target_repo, pr_num)

     print(devq(title))
-    source_repo_url = "git@github.com:{}.git".format(source_repo)
+    source_repo_url = "https://github.com/{}.git".format(source_repo)
     run("git", "fetch", source_repo_url, source_branch+":"+new_local_branch)
     run("git", "branch", "-u", remote+"/"+target_branch, new_local_branch)
     run("git", "checkout", new_local_branch)
```

**Comment by cakoose** [comment]
Yes, HTTPS will always work for public repos, but for private repos, some users will have SSH set up and others will have HTTPS set up.

I changed the code to try and auto-detect.  If the local repo's remote is configured with an SSH URL, we'll use SSH.  Otherwise, use HTTPS.  Lemme know if this doesn't work for you.

**Comment by anntzer** [comment]
Sounds nice, thanks.
